version: "3.8"

services:
  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - static_data:/code/static
    ports:
      - "8000:8000"
    networks:
      - my_net
    env_file:
      - ./.env

  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - my_net
    env_file:
      - ./.env

  nginx:
    # image: nginx:1.19.7-alpine
    build: nginx/
    container_name: nginx
    restart: always
    volumes:
      - static_data:/code/static
    ports:
      - "80:8000"
    networks:
      - my_net
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_data:

networks:
  my_net:
    driver: bridge
