version: "3.8"

services:
  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - static_data:/code/static
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: nginx/
    container_name: nginx
    restart: always
    volumes:
      - static_data:/code/static
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
