version: "3.8"

services:
  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - static_data:/code/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.7-alpine
    container_name: nginx
    restart: always
    volumes:
      - static_data:/code/static
#      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_data:
