version: "3"

services:
  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    image: alexandervernigora/web:latest
    container_name: web
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_data:/code/static
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.7
    container_name: nginx
    restart: always
    volumes:
      - static_data:/code/static
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
